name: rickyshit
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.1


dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.2
  firebase_database: ^11.3.10
  firebase_storage: ^12.3.2

  # API Networking (Equivalent to Retrofit and HttpLoggingInterceptor)
  dio: ^5.4.3+1                           # For Rick & Morty API
  # State Management (Equivalent to ViewModels)
  provider: ^6.1.2                          # For State Management
  # File Handling (Picking PDF/Word docs)
  pdfrx: ^1.0.67    # To view PDFs

  file_picker: ^8.0.3                       # To select PDF/Word documents
  url_launcher: ^6.2.5                      # For opening Word docs
  image_picker: ^1.1.0                      # For selecting Avatars

  # UI & Animations
  lottie: ^3.1.2

  # Equivalent to Glide
  cached_network_image: ^3.4.1

  # For In-App Reading
  webview_flutter: ^4.10.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - images/images/
    - images/lottie/
